document.addEventListener('DOMContentLoaded', () => {

    // --- 1. Lenis Smooth Scroll ---
    const lenis = new Lenis({
        duration: 1.2,
        easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)), // smooth cubic-bezier alike
        direction: 'vertical',
        gestureDirection: 'vertical',
        smooth: true,
        smoothTouch: false,
        touchMultiplier: 2,
    });

    function raf(time) {
        lenis.raf(time);
        requestAnimationFrame(raf);
    }
    requestAnimationFrame(raf);

    // --- 2. Magnetic Buttons ---
    const magneticElements = document.querySelectorAll('.btn-primary, .skill-card, .btn-icon');
    magneticElements.forEach(elem => {
        elem.addEventListener('mousemove', (e) => {
            const rect = elem.getBoundingClientRect();
            const x = e.clientX - rect.left - rect.width / 2;
            const y = e.clientY - rect.top - rect.height / 2;
            // Very light magnetism (max distance 15-20px effect)
            const power = 0.2; 
            
            elem.style.transform = `translate(${x * power}px, ${y * power}px) scale(1.02)`;
            elem.style.transition = 'transform 0.1s cubic-bezier(0.2, 0.8, 0.2, 1)';
        });
        
        elem.addEventListener('mouseleave', () => {
            elem.style.transform = 'translate(0px, 0px) scale(1)';
            elem.style.transition = 'transform 0.6s cubic-bezier(0.2, 0.8, 0.2, 1)';
        });
    });

    // --- 3. App Logic & Elements ---
    const views = {
        hero: document.getElementById('view-hero'),
        skills: document.getElementById('view-skills'),
        loading: document.getElementById('view-loading')
    };
    
    const btns = {
        begin: document.getElementById('btn-begin'),
        backHero: document.getElementById('btn-back-hero'),
        generate: document.getElementById('btn-generate')
    };

    const skillCards = document.querySelectorAll('.skill-card');
    const countDisplay = document.getElementById('count-display');
    const bottomBar = document.querySelector('.bottom-action-bar');
    const loadingSubtitle = document.getElementById('loading-subtitle');

    let selectedSkills = new Set();
    const loadingTexts = [
        "Analyzing selected domains...",
        "Scanning for known vulnerabilities...",
        "Identifying common blindspots...",
        "Calibrating AI logic...",
        "Generating unique scenario graph..."
    ];

    // --- 4. Navigation Logic ---
    const switchView = (fromView, toView) => {
        fromView.classList.remove('active-view');
        // Wait for exit transition
        setTimeout(() => {
            fromView.classList.add('hidden-view');
            toView.classList.remove('hidden-view');
            // Small reflow delay
            setTimeout(() => {
                toView.classList.add('active-view');
            }, 50);
        }, 300); // 300ms matches css transition roughly
    };

    // --- 5. Events ---
    btns.begin.addEventListener('click', () => {
        switchView(views.hero, views.skills);
        checkSelection(); // trigger bar if they went back and forward
    });

    btns.backHero.addEventListener('click', () => {
        switchView(views.skills, views.hero);
        bottomBar.classList.remove('visible');
    });

    // --- 6. Skill Selection Logic ---
    skillCards.forEach(card => {
        card.addEventListener('click', () => {
            const skill = card.dataset.skill;
            if (selectedSkills.has(skill)) {
                selectedSkills.delete(skill);
                card.classList.remove('selected');
            } else {
                selectedSkills.add(skill);
                card.classList.add('selected');
            }
            checkSelection();
        });
    });

    function checkSelection() {
        const count = selectedSkills.size;
        countDisplay.textContent = count;
        
        if (count > 0) {
            bottomBar.classList.add('visible');
            btns.generate.disabled = false;
        } else {
            bottomBar.classList.remove('visible');
            btns.generate.disabled = true;
        }
    }

    // --- 7. MOCK QUESTION BANK ---
    // In production, this data is continuously generated by Groq LLaMA to ensure 100% uniqueness.
    // For this prototype, we mock a large set of varied scenarios.
    const MOCK_DB = {
        'online-safety': [
            { q: "You receive an SMS: 'Dear HDFC customer, your account is suspended. Update KYC here: http://hdfc-kyc-update.xyz'. What is the FIRST indicator of a scam?", opts: ["It was sent via SMS instead of Email", "The URL uses .xyz instead of an official domain", "It asks to update KYC", "They used 'Dear customer' instead of your name"], ans: 1 },
            { q: "Which password behavior is the highest security risk?", opts: ["Using a 8-character password with symbols", "Writing a password on a sticky note at home", "Reusing the same strong password for your email and social media", "Changing your password every 30 days"], ans: 2 }
        ],
        'misinformation': [
            { q: "A viral WhatsApp forward shows a video of a politician saying something controversial. What's the best way to verify if it's a deepfake?", opts: ["Check if the lips sync perfectly with the audio", "Forward it to 5 friends to see what they think", "Look for unnatural lighting, blink rates, and cross-reference with major news outlets", "Use a reverse text search on Google"], ans: 2 },
            { q: "You read an article claiming a new superfood cures all known diseases. It cites a 'recent study' but provides no link. This is an example of:", opts: ["Confirmation bias", "Clickbait", "Pseudoscience without verified sourcing", "Satire"], ans: 2 }
        ],
        'privacy': [
            { q: "A new flashlight app requests access to your Contacts and Microphone. What should you do?", opts: ["Accept, maybe it uses voice commands", "Deny and uninstall, a flashlight does not need these permissions", "Accept but turn off microphone later", "Only allow while using the app"], ans: 1 },
            { q: "When you browse in 'Incognito' or 'Private' mode, what is actually happening?", opts: ["You are completely invisible to your ISP", "Websites cannot track your IP address", "Your browser does not save your local search history or cookies", "Your connection is encrypted automatically"], ans: 2 }
        ],
        'social-media': [
            { q: "Which scenario describes an 'Algorithm Filter Bubble'?", opts: ["Instagram only showing you posts that agree with your existing political views", "A hacker locking you out of your account", "When your posts get fewer likes than usual (Shadowbanning)", "A new feature on TikTok for organizing videos"], ans: 0 },
            { q: "A friend posts a photo of your group, but it reveals your location and home address in the background. What is the most literate action?", opts: ["Report the photo to Instagram", "Comment angrily", "Private message them to take it down immediately due to doxxing risks", "Save the photo and ignore it"], ans: 2 }
        ],
        'search-skills': [
            { q: "If you want to search for the exact phrase 'climate change effects' only on educational websites, what should you type in Google?", opts: ["climate change effects educational", "site:.edu \"climate change effects\"", "climate change effects OR .edu", "inurl:climate change intext:edu"], ans: 1 },
            { q: "Which source is generally considered most reliable for academic research?", opts: ["Wikipedia.org", "A blog post by a known influencer", "A peer-reviewed journal article on JSTOR", "A company's official 'About Us' page"], ans: 2 }
        ],
        'coding-basics': [
            { q: "What does HTML stand for in web development?", opts: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyperlink and Text Management Logic", "Home Tool Markup Language"], ans: 0 },
            { q: "You want a computer to repeat a task 10 times. Which programming concept would you use?", opts: ["An IF statement", "A Variable", "A Loop (like 'for' or 'while')", "An Array"], ans: 2 }
        ]
    };

    // --- 8. Assessment Flow Logic ---
    let currentQuestions = [];
    let currentQuestionIndex = 0;
    let userAnswers = []; // Store { qObj, passed: boolean }

    btns.generate.addEventListener('click', () => {
        bottomBar.classList.remove('visible');
        switchView(views.skills, views.loading);

        let textIndex = 0;
        const textInterval = setInterval(() => {
            textIndex = (textIndex + 1) % loadingTexts.length;
            loadingSubtitle.style.opacity = 0;
            setTimeout(() => {
                loadingSubtitle.textContent = loadingTexts[textIndex];
                loadingSubtitle.style.opacity = 1;
            }, 300);
        }, 1500);

        // Build unique question set from selected skills
        currentQuestions = [];
        Array.from(selectedSkills).forEach(skill => {
            const skillQs = MOCK_DB[skill];
            if (skillQs) {
                // Shuffle questions for this skill to ensure variety
                const shuffled = [...skillQs].sort(() => 0.5 - Math.random());
                // Pick up to 2 random questions per selected category for the demo
                const selected = shuffled.slice(0, 2).map(q => ({...q, skillCategory: skill})); 
                currentQuestions = currentQuestions.concat(selected);
            }
        });
        
        // Final shuffle of the whole set
        currentQuestions.sort(() => 0.5 - Math.random());
        
        currentQuestionIndex = 0;
        userAnswers = [];

        // Mock AI Generation Delay
        setTimeout(() => {
            clearInterval(textInterval);
            renderQuestion(0);
            switchView(views.loading, views.assessment); 
        }, 3000);
    });

    const questionCounter = document.getElementById('question-counter');
    const currentSkillBadge = document.getElementById('current-skill-badge');
    const questionText = document.getElementById('question-text');
    const optionsContainer = document.getElementById('options-container');
    const progressFill = document.getElementById('progress-fill');
    const btnNextQuestion = document.getElementById('btn-next-question');
    const assessmentActionBar = document.getElementById('assessment-action-bar');
    
    let currentSelectedOptionIndex = null;

    function renderQuestion(index) {
        currentSelectedOptionIndex = null;
        btnNextQuestion.disabled = true;
        assessmentActionBar.style.display = 'flex'; // show bar
        
        const qObj = currentQuestions[index];
        questionCounter.textContent = `Question ${index + 1} of ${currentQuestions.length}`;
        currentSkillBadge.textContent = qObj.skillCategory.replace('-', ' ').toUpperCase();
        questionText.textContent = qObj.q;
        
        // Update progress bar
        const progressPct = ((index) / currentQuestions.length) * 100;
        progressFill.style.width = `${progressPct}%`;

        // Render Options
        optionsContainer.innerHTML = '';
        const letters = ['A', 'B', 'C', 'D'];
        qObj.opts.forEach((optText, i) => {
            const optElem = document.createElement('div');
            optElem.className = 'option-card';
            optElem.innerHTML = `
                <div class="option-letter">${letters[i]}</div>
                <div class="option-text">${optText}</div>
            `;
            
            optElem.addEventListener('click', () => {
                // Deselect others
                document.querySelectorAll('.option-card').forEach(el => el.classList.remove('selected'));
                optElem.classList.add('selected');
                currentSelectedOptionIndex = i;
                btnNextQuestion.disabled = false;
            });
            
            optionsContainer.appendChild(optElem);
        });
    }

    btnNextQuestion.addEventListener('click', () => {
        const qObj = currentQuestions[currentQuestionIndex];
        const isCorrect = currentSelectedOptionIndex === qObj.ans;
        
        userAnswers.push({
            skill: qObj.skillCategory,
            isCorrect: isCorrect
        });

        currentQuestionIndex++;
        
        if (currentQuestionIndex < currentQuestions.length) {
            renderQuestion(currentQuestionIndex);
        } else {
            // Finish
            progressFill.style.width = `100%`;
            finishAssessment();
        }
    });

    // --- 9. Results & Chart Logic ---
    function finishAssessment() {
        switchView(views.assessment, views.results);
        
        // Calculate Scores
        let correctCount = 0;
        const skillScores = {}; // { 'online-safety': { total: 2, correct: 1 }, ... }
        
        userAnswers.forEach(ans => {
            if (ans.isCorrect) correctCount++;
            
            if (!skillScores[ans.skill]) {
                skillScores[ans.skill] = { total: 0, correct: 0 };
            }
            skillScores[ans.skill].total++;
            if (ans.isCorrect) skillScores[ans.skill].correct++;
        });

        const overallScorePct = Math.round((correctCount / currentQuestions.length) * 100);
        
        // Update DOM
        document.getElementById('final-score').textContent = `${overallScorePct}%`;
        
        // Circular Progress CSS hack
        document.querySelector('.circular-progress').style.setProperty('--progress', overallScorePct);
        
        const levelBadgeText = document.getElementById('final-level-text');
        const levelBadgeIcon = document.querySelector('.level-icon');
        const levelBadge = document.getElementById('final-level-badge');
        
        if (overallScorePct >= 90) {
            levelBadgeText.textContent = "Digital Champion";
            levelBadgeIcon.textContent = "👑";
            levelBadge.style.background = "linear-gradient(135deg, rgba(16, 185, 129, 0.2), rgba(20, 184, 166, 0.1))";
            levelBadge.style.borderColor = "var(--color-teal)";
        } else if (overallScorePct >= 70) {
            levelBadgeText.textContent = "Digital Native";
            levelBadgeIcon.textContent = "🛡️";
            levelBadge.style.background = "linear-gradient(135deg, rgba(59, 130, 246, 0.2), rgba(99, 102, 241, 0.1))";
            levelBadge.style.borderColor = "var(--color-blue)";
        } else if (overallScorePct >= 40) {
            levelBadgeText.textContent = "Digital Explorer";
            levelBadgeIcon.textContent = "🧭";
            levelBadge.style.background = "linear-gradient(135deg, rgba(245, 158, 11, 0.2), rgba(249, 115, 22, 0.1))";
            levelBadge.style.borderColor = "var(--color-orange)";
        } else {
            levelBadgeText.textContent = "Digital Novice";
            levelBadgeIcon.textContent = "🌱";
            levelBadge.style.background = "linear-gradient(135deg, rgba(244, 63, 94, 0.2), rgba(225, 29, 72, 0.1))";
            levelBadge.style.borderColor = "var(--color-red)";
        }

        // Render Radar Chart
        initRadarChart(skillScores);
    }

    let radarChartInstance = null;

    function initRadarChart(skillScores) {
        const ctx = document.getElementById('radarChart').getContext('2d');
        
        const labels = Object.keys(skillScores).map(k => k.replace('-', ' ').toUpperCase());
        const data = Object.values(skillScores).map(v => (v.correct / v.total) * 100);

        if (radarChartInstance) radarChartInstance.destroy();

        radarChartInstance = new Chart(ctx, {
            type: 'radar',
            data: {
                labels: labels,
                datasets: [{
                    label: 'Proficiency',
                    data: data,
                    backgroundColor: 'rgba(139, 92, 246, 0.4)',
                    borderColor: '#8b5cf6',
                    pointBackgroundColor: '#2dd4bf',
                    pointBorderColor: '#fff',
                    pointHoverBackgroundColor: '#fff',
                    pointHoverBorderColor: '#2dd4bf',
                    borderWidth: 2,
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                    r: {
                        angleLines: { color: 'rgba(255, 255, 255, 0.1)' },
                        grid: { color: 'rgba(255, 255, 255, 0.1)' },
                        pointLabels: {
                            color: '#a1a1aa',
                            font: { family: 'Satoshi', size: 12, weight: '500' }
                        },
                        ticks: {
                            display: false, // hide the numbers (0, 20, 40 etc)
                            min: 0,
                            max: 100,
                            stepSize: 20
                        }
                    }
                },
                plugins: {
                    legend: { display: false },
                    tooltip: {
                        backgroundColor: 'rgba(24, 24, 27, 0.9)',
                        titleFont: { family: 'Satoshi', size: 14 },
                        bodyFont: { family: 'Geist', size: 14 },
                        padding: 12,
                        cornerRadius: 8,
                        displayColors: false,
                        callbacks: {
                            label: function(context) {
                                return `Score: ${context.parsed.r}%`;
                            }
                        }
                    }
                }
            }
        });
    }

    // --- 10. AI Mentor Chat Logic ---
    const btnOpenChat = document.getElementById('btn-open-chat');
    const btnCloseChat = document.getElementById('btn-close-chat');
    const chatDrawer = document.getElementById('chat-drawer');
    const chatBackdrop = document.getElementById('chat-backdrop');
    const chatInput = document.getElementById('chat-input');
    const btnSendMessage = document.getElementById('btn-send-message');
    const chatMessages = document.getElementById('chat-messages');

    function toggleChat() {
        const isOpen = chatDrawer.classList.contains('open');
        if (isOpen) {
            chatDrawer.classList.remove('open');
            chatBackdrop.classList.remove('visible');
        } else {
            chatDrawer.classList.add('open');
            chatBackdrop.classList.add('visible');
            setTimeout(() => chatInput.focus(), 300);
        }
    }

    if (btnOpenChat) btnOpenChat.addEventListener('click', toggleChat);
    if (btnCloseChat) btnCloseChat.addEventListener('click', toggleChat);
    if (chatBackdrop) chatBackdrop.addEventListener('click', toggleChat);

    function appendMessage(text, isUser) {
        const msgDiv = document.createElement('div');
        msgDiv.className = `message ${isUser ? 'user-message' : 'ai-message'}`;
        msgDiv.innerHTML = `<div class="message-bubble">${text}</div>`;
        chatMessages.appendChild(msgDiv);
        chatMessages.scrollTo({ top: chatMessages.scrollHeight, behavior: 'smooth' });
    }

    function showTypingIndicator() {
        const ind = document.createElement('div');
        ind.className = 'typing-indicator';
        ind.id = 'typing-indicator';
        ind.innerHTML = `<div class="typing-dot"></div><div class="typing-dot"></div><div class="typing-dot"></div>`;
        chatMessages.appendChild(ind);
        chatMessages.scrollTo({ top: chatMessages.scrollHeight, behavior: 'smooth' });
    }

    function removeTypingIndicator() {
        const ind = document.getElementById('typing-indicator');
        if (ind) ind.remove();
    }

    function handleChatSubmit() {
        const text = chatInput.value.trim();
        if (!text) return;
        
        appendMessage(text, true);
        chatInput.value = '';
        
        showTypingIndicator();
        
        // Mock AI response
        setTimeout(() => {
            removeTypingIndicator();
            const responses = [
                "That's a great question! When viewing suspected deepfakes, always look for unnatural blink rates or slight blurs around the edges of the face/mouth.",
                "Yes, using a password manager is highly recommended. It saves you from reusing passwords and creating a single point of failure.",
                "Absolutely. I can also generate a custom reading list for you if you want to dive deeper into privacy laws like GDPR."
            ];
            const reply = responses[Math.floor(Math.random() * responses.length)];
            appendMessage(reply, false);
        }, 2000);
    }

    if (btnSendMessage) btnSendMessage.addEventListener('click', handleChatSubmit);
    if (chatInput) {
        chatInput.addEventListener('keypress', (e) => {
            if (e.key === 'Enter') handleChatSubmit();
        });
    }

});
